name: Docker
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag Name'     
        required: true
        default: 'latest'

jobs:

  build:
    name: docker-ci
    
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build the loxi-ccm image
      run: ./build.sh 
        
    - name: Build the latest loxilb Docker image
      if: github.event.inputs.tagName == ''
      run: docker build . --tag ghcr.io/loxilb-io/loxi-ccm:latest
      
    - name: Build the loxilb Docker image with given tag
      if: github.event.inputs.tagName != ''
      run: docker build . --tag ghcr.io/loxilb-io/loxi-ccm:${{ github.event.inputs.tagName }}

    - name: Publish the latest loxilb Docker image
      if: | 
          github.repository == 'loxilb-io/loxi-ccm' 
          &&  github.event.inputs.tagName == ''
      run: docker push ghcr.io/loxilb-io/loxi-ccm:latest
      
    - name: Publish the loxilb Docker image with given tag
      if: |
          github.repository == 'loxilb-io/loxi-ccm'
          &&  github.event.inputs.tagName != ''
      run: docker push ghcr.io/loxilb-io/loxi-ccm:${{ github.event.inputs.tagName }} 
